### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by MikeRalphson** [brandonlw/drivecom#3]
I'm trying to use this on an ASUS Transformer T100TA, which I'm lead to believe has a Phison USB controller with an 8gb flash drive, originally used for the recovery partition. I'm running Ubuntu on it now. It's definitely available (read-only) on `/dev/sda`

```
sudo python3 ./drivecom.py get_info --path /dev/sda
drivecom.py - Phison USB flasher and utilities
----------------------------------------------
Handling command 'get_info'...

Using USB drive:
	Path: /dev/sda

Traceback (most recent call last):
  File "./drivecom.py", line 652, in <module>
    args.func(args)
  File "./drivecom.py", line 391, in drivecom_get_info
    ret = device.send_scsi_command([0x06, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01], 512 + 16)
  File "./drivecom.py", line 265, in send_scsi_command
    ret = fcntl.ioctl(self.device_handle, SG_IO, args)
OSError: [Errno 22] Invalid argument
```

Does this mean it's the wrong kind of controller, or do I need to use a different device?

`list_devices` fails with

```
libusb is not set up or installed properly.
```

Even though it (and the dev headers) are installed ok. Does it need 'setup'?

**Comment by MikeRalphson** [comment]
Sorry, just reread Readme, will try /dev/sg...

**Comment by MikeRalphson** [comment]
Just for anyone else who finds this, it worked with `--path /dev/sg0`

```
drivecom.py - Phison USB flasher and utilities
----------------------------------------------
Handling command 'get_info'...

Using USB drive:
	Path: /dev/sg0

Image version: 01.00.53
Chip type: 2268
Flash chip ID: 98DE989272D7
Mode: Firmware
```
